name: Tests for hw2
on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    env:
      VALGRIND_OPTS: --leak-check=full --track-origins=yes --show-leak-kinds=all
      CPPLINT_FILTERS: --filter=-build/include_subdir,-readability/casting,-legal/copyright,-build/include_subdir,-whitespace/line_length,-runtime/threadsafe_fn,-build/include,-build/header_guard,-runtime/arrays
      CPPLINT_FILES: --recursive main.c lib/src/ lib/include/ test/
      CPPCHECK_FILES: main.c generator.c generate_data.c test/ lib/include lib/src
      CODECOV_TOKEN: 67c8dccd-21db-40b6-9fd3-d2f1fa59a190



    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update & install packages
        run: |
         apt update && apt upgrade -y && apt install -y gcc-10 cmake g++-10 build-essential cppcheck valgrind python3 python3-pip
         python3 -m pip install cpplint
      - name: Run cpplint
        run: cpplint $CPPLINT_FILTERS $CPPLINT_FILES

      - name: Run cppcheck
        run: cppcheck $CPPCHECK_FILES

      - name: Compile libs
        run: cd lib && cmake . -DCMAKE_INSTALL_PREFIX=~/install && make -j$(nproc)

      - name: Install libs
        run: cd lib && cmake --build . --target install

      - name: Make project
        run: cmake . -Dsingle_DIR=~/install/lib/cmake/Single -Dmulti_DIR=~/install/lib/cmake/Multi && make -j$(nproc)

      - name: Run gtest
        run: make test

      - name: Run Valgrind
        run: valgrind $VALGRIND_OPTS ./hw2
     
      - name: Run Codecov
        run: bash <(curl -s https://codecov.io/bash)
